# Generated by Django 5.1.1 on 2024-11-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=100, unique=True)),
                ('asset_name', models.CharField(choices=[('IS', 'ИС'), ('data', 'Данные'), ('infrastructure', 'Инфраструктура'), ('network', 'Сеть'), ('products', 'Продукты')], default='IS', max_length=255)),
                ('asset_value', models.CharField(choices=[('high_relevant', 'Очень важные'), ('relevant', 'Важные'), ('low_relevant', 'Не очень важные'), ('non_relevant', 'Неважные')], default='non_relevant', max_length=20)),
                ('asset_type', models.CharField(choices=[('material', 'Материальные'), ('intangible', 'Нематериальные')], default='material', max_length=20)),
            ],
        ),
    ]
