# Generated by Django 5.1.1 on 2024-11-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_asset_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAssetValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_asset_value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultAssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_asset_name', models.CharField(max_length=200)),
                ('default_asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetcategory')),
                ('default_asset_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetvalue')),
            ],
        ),
    ]
