# Generated by Django 5.1.1 on 2024-11-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_defaultassetcategory_defaultassetvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultAssetEnum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_asset_element', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='defaultassetmodel',
            name='default_asset_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetenum'),
        ),
    ]
