# Generated by Django 5.1.1 on 2025-01-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_defaultassetenum_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultAssetEnum',
            new_name='DefaultAssetType',
        ),
        migrations.RenameField(
            model_name='defaultassetmodel',
            old_name='default_asset_name',
            new_name='default_asset_type',
        ),
        migrations.RenameField(
            model_name='defaultassettype',
            old_name='default_asset_element',
            new_name='default_asset_type',
        ),
        migrations.AddField(
            model_name='defaultassetmodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
