# Generated by Django 5.1.1 on 2025-01-10 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_defaultassetmodel_company'),
        ('company', '0005_companyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultassetmodel',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.company'),
        ),
    ]
