# Generated by Django 5.1.1 on 2025-01-21 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_defaultassetmodel_company'),
        ('company', '0005_companyuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultassetmodel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='defaultassetmodel',
            name='default_asset_category',
        ),
        migrations.RemoveField(
            model_name='defaultassetmodel',
            name='default_asset_type',
        ),
        migrations.RemoveField(
            model_name='defaultassetmodel',
            name='default_asset_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_name',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_value',
        ),
        migrations.AddField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.company'),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_asset_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetcategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_asset_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassettype'),
        ),
        migrations.AddField(
            model_name='asset',
            name='default_asset_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetvalue'),
        ),
        migrations.AddField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
