# Generated by Django 5.1.1 on 2025-01-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_remove_defaultassetmodel_company_and_more'),
        ('vulnerability', '0009_remove_defaultvulnerability_relevant_asset_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultAssetModel',
        ),
    ]
