# Generated by Django 5.1.1 on 2025-01-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_delete_defaultassetmodel'),
        ('company', '0005_companyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.company'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassettype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetvalue'),
        ),
    ]
