# Generated by Django 5.1.1 on 2025-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_company_and_more'),
        ('vulnerability', '0014_remove_defaultvulnerability_related_asset_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='default_asset_category',
        ),
        migrations.AddField(
            model_name='asset',
            name='default_vulnerabilities',
            field=models.ManyToManyField(related_name='assets', to='vulnerability.defaultvulnerability'),
        ),
        migrations.AddField(
            model_name='asset',
            name='vulnerabilities',
            field=models.ManyToManyField(related_name='assets', to='vulnerability.uservulnerability'),
        ),
    ]
