# Generated by Django 5.1.1 on 2025-02-25 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_remove_asset_default_vulnerabilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='default_asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetcategory'),
        ),
    ]
