# Generated by Django 5.1.1 on 2025-03-06 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_asset_default_asset_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='default_asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetcategory', verbose_name='Категория актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassettype', verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetvalue', verbose_name='Значимость актива'),
        ),
    ]
