# Generated by Django 5.1.1 on 2025-03-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_asset_default_asset_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='default_asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassettype'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='default_asset_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.defaultassetvalue'),
        ),
        migrations.AlterField(
            model_name='defaultassetcategory',
            name='default_asset_category',
            field=models.CharField(max_length=100, verbose_name='Категория актива'),
        ),
        migrations.AlterField(
            model_name='defaultassettype',
            name='default_asset_type',
            field=models.CharField(max_length=100, verbose_name='Тип актива'),
        ),
        migrations.AlterField(
            model_name='defaultassetvalue',
            name='default_asset_value',
            field=models.CharField(max_length=100, verbose_name='Значимость актива'),
        ),
    ]
