# Generated by Django 5.1.1 on 2025-01-28 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_alter_risk_related_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='related_company',
        ),
    ]
