# Generated by Django 5.1.1 on 2025-01-29 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyuser'),
        ('risk', '0005_rename_exploit_possability_risk_exploit_possibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='related_company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
