# Generated by Django 5.1.1 on 2025-01-30 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_alter_risk_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='decision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.riskdecision'),
        ),
    ]
