# Generated by Django 5.1.1 on 2025-01-30 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_alter_risk_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='related_company',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='related_threat',
        ),
        migrations.DeleteModel(
            name='RiskDecision',
        ),
        migrations.DeleteModel(
            name='Risk',
        ),
    ]
