# Generated by Django 5.1.1 on 2025-01-30 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0005_companyuser'),
        ('risk', '0010_remove_risk_decision_remove_risk_related_company_and_more'),
        ('threat', '0011_alter_userthreat_related_asset_companythreat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('related_company', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('related_threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat.userthreat')),
            ],
        ),
    ]
