# Generated by Django 5.1.1 on 2025-01-30 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0011_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='decision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='risk.riskdecision'),
        ),
    ]
