# Generated by Django 5.1.1 on 2025-01-30 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0013_alter_risk_related_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.riskdecision'),
        ),
    ]
