# Generated by Django 5.1.1 on 2025-01-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0014_alter_risk_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='decision',
        ),
    ]
