# Generated by Django 5.1.1 on 2025-01-30 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyuser'),
        ('risk', '0015_remove_risk_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='related_company',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
