# Generated by Django 5.1.1 on 2025-01-31 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0016_alter_risk_related_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='decision',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='risk.riskdecision'),
        ),
    ]
