# Generated by Django 5.1.1 on 2025-03-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0002_defaultmeasure_defaultthreat_defaultvulnerability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulesvuln',
            name='measure',
        ),
        migrations.RemoveField(
            model_name='rulesvuln',
            name='vuln',
        ),
        migrations.DeleteModel(
            name='RulesThreat',
        ),
        migrations.DeleteModel(
            name='RulesVuln',
        ),
    ]
