# Generated by Django 5.1.1 on 2025-03-24 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0003_remove_rulesvuln_measure_remove_rulesvuln_vuln_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.defaultmeasure')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.defaultthreat')),
            ],
        ),
        migrations.CreateModel(
            name='RulesVuln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.defaultmeasure')),
                ('vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.defaultvulnerability')),
            ],
        ),
    ]
