# Generated by Django 5.1.1 on 2025-03-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0004_rulesthreat_rulesvuln'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultthreat',
            name='threat_name',
        ),
        migrations.RemoveField(
            model_name='defaultthreat',
            name='threat_type',
        ),
        migrations.RemoveField(
            model_name='defaultvulnerability',
            name='description',
        ),
        migrations.RemoveField(
            model_name='defaultvulnerability',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='defaultvulnerability',
            name='destruction_of_availability',
        ),
        migrations.RemoveField(
            model_name='defaultvulnerability',
            name='destruction_of_confidence',
        ),
        migrations.RemoveField(
            model_name='defaultvulnerability',
            name='destruction_of_integrity',
        ),
        migrations.RemoveField(
            model_name='defaultvulnerability',
            name='source',
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='destination',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='destruction_of_availability',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='destruction_of_confidence',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='destruction_of_integrity',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='defaultthreat',
            name='source',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
