# Generated by Django 5.1.1 on 2025-03-24 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0005_remove_defaultthreat_threat_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMeasureGroup',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='defaultmeasure',
            name='description',
        ),
        migrations.AddField(
            model_name='defaultmeasure',
            name='related_threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solver.defaultthreat'),
        ),
        migrations.AlterField(
            model_name='defaultmeasure',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='defaultmeasure',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='defaultthreat',
            name='id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DefaultMeasureSubgroup',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solver.defaultmeasuregroup')),
            ],
        ),
        migrations.AddField(
            model_name='defaultmeasure',
            name='subgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solver.defaultmeasuresubgroup'),
        ),
    ]
