# Generated by Django 5.1.1 on 2025-03-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0006_defaultmeasuregroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmeasuresubgroup',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
