# Generated by Django 5.1.1 on 2025-03-24 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0007_alter_defaultmeasuresubgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultmeasuresubgroup',
            name='group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='solver.defaultmeasuregroup'),
        ),
    ]
