# Generated by Django 5.1.1 on 2025-03-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0008_alter_defaultmeasuresubgroup_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultmeasure',
            name='related_threat',
        ),
    ]
