# Generated by Django 5.1.1 on 2025-03-25 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0009_remove_defaultmeasure_related_threat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesthreat',
            name='threat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solver.defaultthreat'),
        ),
    ]
