# Generated by Django 5.1.1 on 2025-03-25 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0010_alter_rulesthreat_threat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesthreat',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.defaultthreat'),
        ),
    ]
