# Generated by Django 5.1.1 on 2025-03-31 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0011_alter_rulesthreat_threat'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralThreats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='GroupWays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='rulesthreat',
            name='threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solver.defaultthreat'),
        ),
        migrations.CreateModel(
            name='ThreatObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_generalthreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.generalthreats')),
                ('id_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.generalobjects')),
            ],
        ),
        migrations.CreateModel(
            name='Ways',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.groupways')),
            ],
        ),
        migrations.CreateModel(
            name='ThreatWays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_generalthreat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.generalthreats')),
                ('id_way', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.ways')),
            ],
        ),
    ]
