# Generated by Django 5.1.1 on 2025-03-31 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0012_generalobjects_generalthreats_groupways_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalthreats',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
