# Generated by Django 5.1.1 on 2025-03-31 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0013_alter_generalthreats_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalthreats',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generalthreats',
            name='name',
        ),
    ]
