# Generated by Django 5.1.1 on 2025-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0014_remove_generalthreats_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalthreats',
            name='description',
            field=models.CharField(default='g', max_length=700),
        ),
        migrations.AddField(
            model_name='generalthreats',
            name='name',
            field=models.CharField(default='g', max_length=200),
        ),
    ]
