# Generated by Django 5.1.1 on 2025-03-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0015_generalthreats_description_generalthreats_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalthreats',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='generalthreats',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
