# Generated by Django 5.1.1 on 2025-03-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0016_alter_generalthreats_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupways',
            name='name',
        ),
        migrations.AlterField(
            model_name='generalthreats',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='groupways',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
