# Generated by Django 5.1.1 on 2025-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0017_remove_groupways_name_alter_generalthreats_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupways',
            name='name',
            field=models.CharField(default='rkjg', max_length=200),
        ),
    ]
