# Generated by Django 5.1.1 on 2025-03-31 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0018_groupways_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupways',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
