# Generated by Django 5.1.1 on 2025-03-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0019_alter_groupways_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ways',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ways',
            name='name',
        ),
        migrations.AlterField(
            model_name='ways',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
