# Generated by Django 5.1.1 on 2025-03-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0020_remove_ways_group_remove_ways_name_alter_ways_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ways',
            name='group',
            field=models.ForeignKey(default='rb', on_delete=django.db.models.deletion.CASCADE, to='solver.groupways'),
        ),
        migrations.AddField(
            model_name='ways',
            name='name',
            field=models.CharField(default='rb', max_length=200),
        ),
    ]
