# Generated by Django 5.1.1 on 2025-03-31 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0021_ways_group_ways_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ways',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.groupways'),
        ),
        migrations.AlterField(
            model_name='ways',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
