# Generated by Django 5.1.1 on 2025-03-31 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0022_alter_ways_group_alter_ways_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalobjects',
            name='description',
        ),
        migrations.RemoveField(
            model_name='generalobjects',
            name='name',
        ),
        migrations.AlterField(
            model_name='generalobjects',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
