# Generated by Django 5.1.1 on 2025-03-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0025_alter_generalobjects_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threatobject',
            name='id_generalthreat',
        ),
    ]
