# Generated by Django 5.1.1 on 2025-03-31 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0028_alter_threatobject_id_generalthreat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ways',
            name='group',
        ),
    ]
