# Generated by Django 5.1.1 on 2025-03-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0029_remove_ways_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ways',
            name='group',
            field=models.ForeignKey(default='gb', on_delete=django.db.models.deletion.CASCADE, to='solver.groupways'),
        ),
    ]
