# Generated by Django 5.1.1 on 2025-03-31 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0030_ways_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ways',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.groupways'),
        ),
    ]
