# Generated by Django 5.1.1 on 2025-04-01 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0031_alter_ways_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatways',
            old_name='id_generalthreat',
            new_name='generalthreat',
        ),
        migrations.RenameField(
            model_name='threatways',
            old_name='id_way',
            new_name='way',
        ),
        migrations.CreateModel(
            name='UserRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('general_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.generalobjects')),
                ('threat_ways', models.ManyToManyField(to='solver.threatways')),
                ('threats', models.ManyToManyField(to='solver.generalthreats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
