# Generated by Django 5.1.1 on 2025-04-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0032_rename_id_generalthreat_threatways_generalthreat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatways',
            old_name='generalthreat',
            new_name='generalthreat_id',
        ),
        migrations.RenameField(
            model_name='threatways',
            old_name='way',
            new_name='way_id',
        ),
    ]
