# Generated by Django 5.1.1 on 2025-04-01 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0034_remove_threatways_generalthreat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatways',
            name='generalthret',
            field=models.ForeignKey(default='vug', on_delete=django.db.models.deletion.CASCADE, to='solver.generalthreats'),
        ),
        migrations.AddField(
            model_name='threatways',
            name='way',
            field=models.ForeignKey(default='vug', on_delete=django.db.models.deletion.CASCADE, to='solver.ways'),
        ),
    ]
