# Generated by Django 5.1.1 on 2025-04-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0036_alter_threatways_generalthret_alter_threatways_way'),
    ]

    operations = [
        migrations.RenameField(
            model_name='threatways',
            old_name='generalthret',
            new_name='generalthreat',
        ),
    ]
