# Generated by Django 5.1.1 on 2025-04-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0037_rename_generalthret_threatways_generalthreat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrisk',
            old_name='threat_ways',
            new_name='ways',
        ),
    ]
