# Generated by Django 5.1.1 on 2025-04-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0038_rename_threat_ways_userrisk_ways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrisk',
            name='ways',
            field=models.ManyToManyField(to='solver.ways'),
        ),
    ]
