# Generated by Django 5.1.1 on 2025-04-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0040_userrisk_money_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrisk',
            name='name',
            field=models.CharField(default='Rosk #1', max_length=150),
        ),
        migrations.AlterField(
            model_name='userrisk',
            name='money_loss',
            field=models.FloatField(),
        ),
    ]
