# Generated by Django 5.1.1 on 2025-04-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0042_rulesthreat_num_alter_userrisk_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesthreat',
            name='num',
            field=models.CharField(max_length=4),
        ),
    ]
