# Generated by Django 5.1.1 on 2025-04-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0043_alter_rulesthreat_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rulesthreat',
            name='threat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='solver.generalthreats'),
        ),
        migrations.DeleteModel(
            name='RulesVuln',
        ),
    ]
