# Generated by Django 5.1.1 on 2025-04-09 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0044_alter_rulesthreat_threat_delete_rulesvuln'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RulesThreat',
        ),
    ]
