# Generated by Django 5.1.1 on 2025-04-09 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0048_rulesthreat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RulesThreat',
        ),
    ]
