# Generated by Django 5.1.1 on 2025-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0052_rulesthreat'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalthreats',
            name='possibility',
            field=models.FloatField(default=0.5),
        ),
    ]
