# Generated by Django 5.1.1 on 2025-04-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0053_generalthreats_possibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalthreats',
            old_name='possibility',
            new_name='possibility_of_occurrence',
        ),
        migrations.AddField(
            model_name='generalthreats',
            name='possibility_of_success',
            field=models.FloatField(default=0.5),
        ),
    ]
