# Generated by Django 5.1.1 on 2025-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0054_rename_possibility_generalthreats_possibility_of_occurrence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmeasure',
            name='koef',
            field=models.FloatField(default=0.5),
        ),
    ]
