# Generated by Django 5.1.1 on 2025-04-21 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyuser_user'),
        ('solver', '0055_defaultmeasure_koef'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrisk',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
