# Generated by Django 5.1.1 on 2025-04-22 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyuser_user'),
        ('solver', '0056_userrisk_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrisk',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
