# Generated by Django 5.1.1 on 2025-01-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('risk', '0018_risk_related_vulnerability'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=1000)),
                ('related_risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk.risk')),
            ],
        ),
    ]
