# Generated by Django 5.1.1 on 2025-01-31 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_companyuser'),
        ('measure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeasure',
            name='related_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
