# Generated by Django 5.1.1 on 2025-01-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0003_alter_usermeasure_related_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeasure',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
