# Generated by Django 5.1.1 on 2025-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0004_alter_usermeasure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeasure',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
