# Generated by Django 5.1.1 on 2025-03-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0005_alter_usermeasure_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
    ]
