# Generated by Django 5.1.1 on 2025-03-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0007_defaultmeasure_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultMeasure',
        ),
    ]
