# Generated by Django 5.1.1 on 2025-05-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0009_defaultmeasure'),
        ('solver', '0057_alter_userrisk_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermeasure',
            name='related_risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.userrisk'),
        ),
    ]
