# Generated by Django 5.1.1 on 2025-01-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0009_alter_asset_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('related_assets', models.ManyToManyField(to='assets.asset')),
            ],
        ),
    ]
