# Generated by Django 5.1.1 on 2025-01-24 06:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_company_and_more'),
        ('threat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userthreat',
            name='related_assets',
        ),
        migrations.AddField(
            model_name='userthreat',
            name='possability',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='userthreat',
            name='related_asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
    ]
