# Generated by Django 5.1.1 on 2025-01-23 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthreat',
            name='possability',
            field=models.FloatField(default=50, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
