# Generated by Django 5.1.1 on 2025-01-23 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0002_userthreat_possability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthreat',
            name='possability',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
