# Generated by Django 5.1.1 on 2025-01-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0002_remove_userthreat_related_assets_and_more'),

    ]

    operations = [

    ]
