# Generated by Django 5.1.1 on 2025-01-27 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0004_merge_20250127_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userthreat',
            old_name='possability',
            new_name='possibility',
        ),
    ]
