# Generated by Django 5.1.1 on 2025-01-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0006_rename_possibility_userthreat_possability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userthreat',
            old_name='possability',
            new_name='possibility',
        ),
    ]
