# Generated by Django 5.1.1 on 2025-01-27 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0007_rename_possability_userthreat_possibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userthreat',
            old_name='possibility',
            new_name='possability',
        ),
    ]
