# Generated by Django 5.1.1 on 2025-01-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0003_alter_userthreat_possability'),
        ('threat', '0008_rename_possibility_userthreat_possability'),
    ]

    operations = [
    ]
