# Generated by Django 5.1.1 on 2025-01-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0009_merge_20250129_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userthreat',
            old_name='possability',
            new_name='possibility',
        ),
    ]
