# Generated by Django 5.1.1 on 2025-01-29 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_asset_company_and_more'),
        ('company', '0005_companyuser'),
        ('threat', '0010_rename_possability_userthreat_possibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthreat',
            name='related_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset'),
        ),
        migrations.CreateModel(
            name='CompanyThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat.userthreat')),
            ],
            options={
                'unique_together': {('company', 'threat')},
            },
        ),
    ]
