# Generated by Django 5.1.1 on 2025-01-30 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0011_alter_userthreat_related_asset_companythreat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userthreat',
            name='possibility',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
