# Generated by Django 5.1.1 on 2025-03-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0012_alter_userthreat_possibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=150)),
            ],
        ),
    ]
