# Generated by Django 5.1.1 on 2025-03-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0013_threattype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threattype',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
