# Generated by Django 5.1.1 on 2025-03-18 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyuser_user'),
        ('threat', '0016_alter_defaultthreat_threat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userthreat',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='userthreat',
            name='possibility',
            field=models.FloatField(),
        ),
    ]
