# Generated by Django 5.1.1 on 2025-03-18 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0017_userthreat_company_alter_userthreat_possibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultthreat',
            name='threat_type',
        ),
        migrations.RemoveField(
            model_name='userthreat',
            name='company',
        ),
        migrations.AlterField(
            model_name='userthreat',
            name='possibility',
            field=models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.DeleteModel(
            name='ThreatType',
        ),
    ]
