# Generated by Django 5.1.1 on 2025-03-19 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_asset_default_asset_category_and_more'),
        ('threat', '0018_remove_defaultthreat_threat_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetThreat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('threat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='threat.userthreat')),
            ],
            options={
                'unique_together': {('asset', 'threat')},
            },
        ),
    ]
