# Generated by Django 5.1.1 on 2025-03-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat', '0019_assetthreat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userthreat',
            name='related_asset',
        ),
    ]
