# Generated by Django 5.1.1 on 2025-04-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measure', '0009_defaultmeasure'),
        ('solver', '0055_defaultmeasure_koef'),
        ('task', '0002_alter_task_start_date_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='related_measure',
        ),
        migrations.AddField(
            model_name='task',
            name='default_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='solver.defaultmeasure'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='measure.usermeasure'),
        ),
    ]
