# Generated by Django 5.1.1 on 2025-04-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_task_related_measure_task_default_measure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='related_company',
        ),
    ]
