# Generated by Django 5.1.2 on 2025-04-30 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0057_alter_userrisk_company'),
        ('task', '0008_alter_task_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='user_risk',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='solver.userrisk'),
        ),
    ]
