# Generated by Django 5.1.2 on 2025-04-30 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyuser_user'),
        ('solver', '0057_alter_userrisk_company'),
        ('task', '0011_alter_task_user_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='company.company'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='solver.userrisk'),
        ),
    ]
