# Generated by Django 5.1.2 on 2025-04-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_company_alter_task_user_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user_risk',
        ),
    ]
