# Generated by Django 5.1.2 on 2025-04-30 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companyuser_user'),
        ('solver', '0057_alter_userrisk_company'),
        ('task', '0013_remove_task_company_remove_task_user_risk'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='company.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='user_risk',
            field=models.ForeignKey(blank=True, default=6, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='solver.userrisk'),
        ),
    ]
