# Generated by Django 5.1.2 on 2025-04-30 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0057_alter_userrisk_company'),
        ('task', '0014_task_company_task_user_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.AlterField(
            model_name='task',
            name='user_risk',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='solver.userrisk'),
        ),
    ]
