# Generated by Django 5.1.1 on 2025-05-13 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solver', '0057_alter_userrisk_company'),
        ('task', '0016_alter_task_user_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user_risk',
        ),
        migrations.CreateModel(
            name='TaskRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solver.userrisk')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_relations', to='task.task')),
            ],
            options={
                'unique_together': {('task', 'risk')},
            },
        ),
    ]
